---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: lasse-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: lasse-kafka-node
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
  cassandra:
    image: cassandra:latest
    container_name: lasse-cassandra-db
    depends_on:
      - kafka
    ports:
      - '7000:7000'
      - '9042:9042'
      - '9160:9160' 
    environment: 
      CASSANDRA_BROADCAST_ADDRESS: cassandra
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_CLUSTER_NAME: cassandra_cluster  
  cassandra-load-keyspace:
    container_name: lasse-cassandra-load-keyspace
    image: cassandra:latest
    restart: on-failure
    environment: 
      CASSANDRA_BROADCAST_ADDRESS: cassandra-load-keyspace
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_CLUSTER_NAME: cassandra_cluster
    depends_on:
      - cassandra
    volumes:
      - ./cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo Trying to connect on Cluster... && cqlsh cassandra -f /schema.cql && echo CONNECTION ESTABLISHED!!"
  broker:
    build: .
    image: lasse/broker:0.0.1
    container_name: lasse-data-broker
    depends_on:
      - cassandra
      - cassandra-load-keyspace
    restart: on-failure
    environment: 
      KAFKA_CONNECT_ADDRESS: kafka:29092
      CASSANDRA_CONNECT_PORT: 9042
      CASSANDRA_CONNECT_ADDRESS: cassandra
      CASSANDRA_KEYSPACE: time_series_raw_data
      CASSANDRA_SCHEMA_ACTION: CREATE_IF_NOT_EXISTS
      CASSANDRA_SCHEMA_NAME: data
      CASSANDRA_CLUSTER_NAME: cassandra_cluster
  producer:
    build:
      context: ~/eclipse-workspace/kafkaProducer
      dockerfile: ./Dockerfile
    image: lasse/producer:0.0.1
    container_name: lasse-data-producer
    depends_on:
      - cassandra
      - cassandra-load-keyspace
      - broker
    restart: on-failure
    environment:
      KAFKA_CONNECT_ADDRESS: kafka:29092